version: '3.8'

services:
  php-fpm:
    container_name: website-app-php-fpm
    build:
      context: ./docker/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./app/:/var/www

  nginx:
    container_name: website-app-nginx
    build:
      context: ./docker/nginx
    env_file:
      - ./app/.env
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "5546:80"
      - "543:443"

  encore:
    image: node:19-alpine
    volumes:
      - ./app/:/var/www
    working_dir: /var/www
    command: >
      sh -c "
      npm install
      && yarn encore dev
      "