controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\Index::landingpage

threeDimensional:
    path: /3d
    controller: App\Controller\Index::threeDimensional

flat:
    path: /flat
    controller: App\Controller\Index::flat