name: Build assets

on:
  workflow_call:

jobs:
  build-assets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      # see https://github.com/actions/checkout to set version
      - uses: actions/checkout@v4
      # see https://github.com/actions/setup-node to set version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - run: yarn install
      - run: npm update
      - run: yarn encore production
      # see https://github.com/actions/upload-artifact  to set version
      - uses: actions/upload-artifact@v3
        with:
          name: assets
          path: app/public/build