name: Build assets

on:
  workflow_call:

jobs:
  build-assets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
      - run: yarn install
      - run: npm update
      - run: yarn encore production
      - uses: actions/upload-artifact@latest
        with:
          name: assets
          path: app/public/build