name: Build assets and push to staging branch

# start job manuel
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

# start jobs auto on push
#on:
#  push:
#    branches:
#      - main

jobs:
  pushToBranch:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: ./app
    steps:
      # checkout default branch
      - uses: actions/checkout@latest

      # check if staging branch exist
      # If yes -> remove branch and create staging branch
      # If not -> create staging branch
      - name: check if staging branch exist
        run: |
          _check_branch=$(git ls-remote --heads origin staging)
          if [[ ${_check_branch} ]]
          then
            # remove branch
            git push origin --delete staging

            # create branch
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout -b staging main
            git push --set-upstream origin staging
          else
            # create branch
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout -b staging main
            git push --set-upstream origin staging
          fi

      # checkout branch staging
      - uses: actions/checkout@v3
        with:
          ref: staging

      # build js/css files
      - uses: actions/setup-node@latest
        with:
          node-version: latest
      - run: yarn install
      - run: npm update
      - run: yarn encore production

      # Git add commit and push
      - name: git add -> commit -> push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f public/build
          git commit -m "Add artifact" -a
          git push

#      - name: clanup production branch
#        run: |
#          rm -rf docker .github .gitignore README.md docker-compose.yml
#          rm -rf app/assets app/.gitignore app/.gitignore
#          git commit -m "clanup staging branch" -a
#          git push