name: Build assets and push to staging branch

# start job manuel
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

# start jobs auto on push
#on:
#  push:
#    branches:
#      - main

jobs:
  pushToBranch:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: ./app
    steps:
      # checkout default branch
      - uses: actions/checkout@v3

      # check if staging branch exist. If not -> create staging branch
      - name: check if staging branch exist
        run: |
          _check_branch=$(git ls-remote --heads origin staging)
          if [[ ${_check_branch} ]]
          then
            # git push origin --delete staging
            echo 'branch exist'
          else
            # create branch
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout -b staging main
            git push --set-upstream origin staging
          fi

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout staging branch
        run: git checkout staging

      - name: Merge main into staging
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git merge --allow-unrelated-histories main

      - name: Push changes to staging branch
        run: git push origin staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # merge main branch into staging
#      - name: Merge main -> staging
#        uses: devmasx/merge-branch@master
#        with:
#          type: now
#          from_branch: main
#          target_branch: staging
#          github_token: ${{ github.token }}

      # checkout branch staging
      - uses: actions/checkout@v3
        with:
          ref: staging

      # build js/css files
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn encore production

      # Git add commit and push
      - name: git add -> commit -> push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f public/build
          git commit -m "Add artifact" -a
          git push

#      - name: clanup production branch
#        run: |
#          rm -rf docker .github .gitignore README.md docker-compose.yml
#          rm -rf app/assets app/.gitignore app/.gitignore
#          git commit -m "clanup staging branch" -a
#          git push