name: Test Workflow - ftp upload

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

#on:
#  push:
#    branches:
#      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: Test-Deploy
    environment: ftp-deploy
    defaults:
      run:
        working-directory: ./app
    steps:
      #get staging branch
      - uses: actions/checkout@v3
        with:
          ref: staging

      # install lftp
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

#      - name: Debug
#        run: |
#          ls -al ./
#
#      # Cleanup
#      - name: Cleanup
#        run: |
#          # single files
#          sudo rm -rf \
#            .env \
#            .gitignore \
#            .symfony.local.yaml \
#            composer.json \
#            composer.lock \
#            package-lock.json \
#            package.json \
#            webpack.config.js \
#            yarn.lock
#          # directories
#          sudo rm -rf assets
#
#      - name: Debug
#        run: |
#          ls -al ./

      # Sync files
#      - name: Sync files
#        run: lftp -e "open $FTP_HOST; user $FTP_USER $FTP_PASS; set ftp:ssl-allow no; mirror -R --ignore-time --parallel=10 -v" /
#        env:
#          FTP_HOST: ${{ secrets.HOST }}
#          FTP_USER: ${{ secrets.USER }}
#          FTP_PASS: ${{ secrets.PASS }}

      - name: Clear cache hack
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" $FTP_HOST <<EOF
            set ftp:ssl-allow no
            rm -rf /var/cache/prod
            quit
          EOF
        env:
          FTP_HOST: ${{ secrets.HOST }}
          FTP_USER: ${{ secrets.USER }}
          FTP_PASS: ${{ secrets.PASS }}